USE Proyecto2;
/*LLAMADAS*/
CALL INSERT_CONTINET();
CALL INSERT_REGION();
CALL INSERT_PAIS();
CALL INSERT_FRONTERA();
CALL INSERT_INVENTOR();
CALL INSERT_INVENTO();
CALL INSERT_INVENTO_INVENTO();
CALL INSERT_PROFESIONAL();
CALL INSERT_ASIGNACION_INVENTO();
CALL INSERT_AREA();
CALL INSERT_JEFE_AREA();
CALL INSERT_PROFESIONAL_AREA();
CALL INSERT_ENCUESTA();
CALL INSERT_PREGUNTA();
CALL INSERT_RESPEUSTA();
CALL INSERT_RESPUESTA_CORRECTA();
CALL INSERT_PAIS_RESPUESTA();




