/*NORMALIZE DATA*/

use proyecto2;

DELIMITER $$
CREATE PROCEDURE INSERT_CONTINET()
BEGIN
	INSERT INTO Continente(nombre) 
    (SELECT DISTINCT REGION_PADRE FROM carga3);
END;
$$
CALL

DELIMITER $$
CREATE PROCEDURE INSERT_REGION()
BEGIN
	INSERT INTO Region(nombre, idContinente) 
    (SELECT nombre_region, (SELECT id FROM continente WHERE nombre = C3.REGION_PADRE) as continente FROM carga3 AS C3);
END;
$$

DELIMITER $$
CREATE PROCEDURE INSERT_PAIS()
BEGIN
	INSERT INTO Pais(nombre, poblacion, area, capital, region) 
    SELECT DISTINCT PAIS_DEL_INVENTOR, CAST(POBLACION_DEL_PAIS AS DECIMAL(12,2)) as POBLACION_DEL_PAIS,
	CAST(AREA_EN_KM2 AS DECIMAL(12,2)) as AREA_EN_KM2, CAPITAL, (SELECT id FROM region WHERE nombre = REGION_DEL_PAIS) as id   FROM TEMP T;
END;
$$

DELIMITER $$
CREATE PROCEDURE INSERT_FRONTERA()
BEGIN
	INSERT INTO Frontera(pais, front, norte, sur, este, oeste) 
    SELECT DISTINCT 
	(select id from pais where nombre = PAIS_DEL_INVENTOR) as pais, 
	(select id from pais where nombre = FRONTERA_CON) as frontera,  
	CAST(NORTE AS CHAR), 
	CAST(SUR AS CHAR), 
	CAST(ESTE AS CHAR), 
	CAST(OESTE AS CHAR) 
	FROM TEMP T;
END;
$$

DELIMITER $$
CREATE PROCEDURE INSERT_INVENTOR()
BEGIN
	INSERT INTO Inventor(nombre, pais) 
    SELECT DISTINCT INVENTOR, (SELECT id FROM Pais where nombre = PAIS_DEL_INVENTOR) as pais
	FROM TEMP T
    WHERE INVENTOR != "";
END;
$$


DELIMITER $$
CREATE PROCEDURE INSERT_INVENTO()
BEGIN
	INSERT INTO Invento(nombre, anio, pais) 
	SELECT DISTINCT INVENTO, TRUNCATE(CAST(ANIO_DEL_INVENTO AS DECIMAL(10,2)),0) as anio, (SELECT id FROM Pais where nombre = PAIS_DEL_INVENTO) as pais
	FROM TEMP T
    WHERE INVENTO != "";    
END;
$$


DELIMITER $$
CREATE PROCEDURE INSERT_INVENTO_INVENTO()
BEGIN
	INSERT INTO Inventor_Invento(idInvento, idInventor) 
	SELECT DISTINCT (SELECT id from Invento where nombre = INVENTO and anio = ANIO_DEL_INVENTO), (SELECT id from Inventor where nombre = INVENTOR)
	FROM TEMP T
    WHERE INVENTO != "";    
END;
$$

DELIMITER $$
CREATE PROCEDURE INSERT_PROFESIONAL()
BEGIN
	INSERT INTO Profesional(nombre, salario, contrato, comision) 
	SELECT DISTINCT PROFESIONAL_ASIGANDO_AL_INVENTO, 
	CAST(SALARIO AS DECIMAL(10,2)), 
	STR_TO_DATE(FECHA_CONTRATO_PROFESIONAL, '%d/%m/%Y') AS fecha, 
	TRUNCATE(CAST(COMISION AS DECIMAL(10,2)),0)
	FROM TEMP T
	WHERE PROFESIONAL_ASIGANDO_AL_INVENTO != "" AND COMISION != "";    
	INSERT INTO Profesional(nombre, salario, contrato, comision) 
	SELECT DISTINCT PROFESIONAL_ASIGANDO_AL_INVENTO, 
	CAST(SALARIO AS DECIMAL(10,2)), 
	STR_TO_DATE(FECHA_CONTRATO_PROFESIONAL, '%d/%m/%Y') AS fecha, 
	NULL
	FROM TEMP T
	WHERE PROFESIONAL_ASIGANDO_AL_INVENTO != "" AND COMISION = "";    
END;
$$
      
DELIMITER $$
CREATE PROCEDURE INSERT_ASIGNACION_INVENTO()
BEGIN
	INSERT INTO Asignacion_Invento(profesional, invento) 
	SELECT DISTINCT 
    (SELECT ID FROM Profesional WHERE nombre = PROFESIONAL_ASIGANDO_AL_INVENTO) as id,
	(SELECT ID FROM Invento WHERE nombre = INVENTO AND anio = ANIO_DEL_INVENTO) as invent
	FROM TEMP T
	WHERE INVENTO != "";
END;
$$

DELIMITER $$
CREATE PROCEDURE INSERT_AREA()
BEGIN
	INSERT INTO Area(nombre, rankin, descripcion) 
    SELECT DISTINCT AREA_INVEST_DEL_PROF, RANKING, "" AS DESCRIPCION
    FROM TEMP
	WHERE INVENTO != "";
END;
$$



nombre varchar(100) not null,
	rankin int not null,
    descripcion varchar(150) not null,
    
	






